let prompt_array = [

"Inform - Describe three common uses of a smartphone in engineering.",
"Inform - Describe the purpose of a 3D printer to engineers.",
"Inform - Describe the main parts of a laptop computer and their functions.",
"Inform - Describe how a hydraulic system is used in heavy equipment.",
"Inform - Describe the essential features of a tractor.",
"Inform - Describe why safety goggles are used in a chemistry laboratory.",
"Inform - Describe the basic function of a solar panel.",
"Inform - Describe how engineers use computer-aided design (CAD) software.",
"Inform - Describe the purpose of a bridge support structure.",
"Inform - Describe how a water filtration system works.",
"Inform - Describe different uses of drones in engineering fields.",
"Inform - Describe a battery management system in an electric vehicle.",
"Inform - Describe how sensors are used in modern machines.",
"Inform - Describe the basic function of a robot arm in manufacturing.",
"Inform - Describe the role of a civil engineer in a construction project.",
"Inform - Describe how engineers use computer simulations.",
"Inform - Describe different types of renewable energy systems.",
"Inform - Describe the purpose of a circuit board in an electronic device.",
"Inform - Describe how a GPS system helps farmers.",
"Inform - Describe the function of a cooling system in a computer.",
"Inform - Describe different types of materials used in engineering.",
"Inform - Describe how a wind turbine produces electricity.",
"Inform - Describe the purpose of a safety inspection in a workplace.",
"Inform - Describe how engineers use measurements and data.",
"Inform - Describe a technology that improves daily life.",

"Persuade - Argue why hardhat use should be enforced in amateur construction.",
"Persuade - Argue why engineering students should complete internships.",
"Persuade - Argue why companies should provide regular safety training.",
"Persuade - Argue why electric vehicles are a good investment for the future.",
"Persuade - Argue why all engineering students should learn basic programming.",
"Persuade - Argue why recycling programs should be required in colleges.",
"Persuade - Argue why companies should use more renewable energy.",
"Persuade - Argue why workers should always follow safety procedures.",
"Persuade - Argue why teamwork skills are important for engineers.",
"Persuade - Argue why universities should offer hands-on laboratory courses.",
"Persuade - Argue why students should learn technical writing skills.",
"Persuade - Argue why engineers should consider environmental impacts.",
"Persuade - Argue why companies should replace outdated technology.",
"Persuade - Argue why public transportation should receive more funding.",
"Persuade - Argue why quality testing is necessary before selling products.",
"Persuade - Argue why engineers should study ethics.",
"Persuade - Argue why manufacturers should design products for repair.",
"Persuade - Argue why workplaces should limit unnecessary meetings.",
"Persuade - Argue why cybersecurity training is needed in agriculture.",
"Persuade - Argue why machines should receive regular maintenance.",
"Persuade - Argue why companies should hire diverse engineering teams.",
"Persuade - Argue why students should participate in engineering clubs.",
"Persuade - Argue why safety equipment should be free for workers.",
"Persuade - Argue why automation can improve workplace efficiency.",
"Persuade - Argue why engineers should communicate clearly with non-engineers.",

"Guide - Explain how to save a file in Microsoft Word.",
"Guide - Explain how to create a strong password for an online account.",
"Guide - Explain how to organize files on a computer.",
"Guide - Explain how to submit an assignment using Canvas.",
"Guide - Explain how to measure an object using a ruler or caliper.",
"Guide - Explain how to safely use a power drill.",
"Guide - Explain how to prepare for a laboratory experiment.",
"Guide - Explain how to create a simple spreadsheet in Excel.",
"Guide - Explain how to connect a computer to a wireless network.",
"Guide - Explain how to print a document from a computer.",
"Guide - Explain how to check the battery level on a device.",
"Guide - Explain how to read a basic engineering drawing.",
"Guide - Explain how to create a presentation slide.",
"Guide - Explain how to install software on a computer.",
"Guide - Explain how to safely enter a construction site.",
"Guide - Explain how to use a fire extinguisher.",
"Guide - Explain how to perform a basic equipment inspection.",
"Guide - Explain how to collect data during an experiment.",
"Guide - Explain how to write a professional email to an instructor.",
"Guide - Explain how to create a folder for an engineering project.",
"Guide - Explain how to back up important files.",
"Guide - Explain how to use a calculator for engineering equations.",
"Guide - Explain how to prepare a machine before operation.",
"Guide - Explain how to follow instructions in a technical manual.",
"Guide - Explain how to troubleshoot a simple computer problem.",

"Catalogue - List different engineering majors and their career opportunities.",
"Catalogue - List different majors that can lead to careers in biochemistry.",
"Catalogue - List different types of renewable energy careers.",
"Catalogue - List different types of engineers and their responsibilities.",
"Catalogue - List different types of computer software used by engineers.",
"Catalogue - List different types of construction equipment.",
"Catalogue - List different materials used in manufacturing.",
"Catalogue - List different types of sensors and their applications.",
"Catalogue - List different careers available in mechanical engineering.",
"Catalogue - List different types of transportation systems.",
"Catalogue - List different types of robots used in industry.",
"Catalogue - List different laboratory tools used by engineers.",
"Catalogue - List different types of batteries and their uses.",
"Catalogue - List different programming languages used in engineering.",
"Catalogue - List different types of bridges and their designs.",
"Catalogue - List different workplace safety equipment.",
"Catalogue - List different types of renewable energy technologies.",
"Catalogue - List different types of engineering projects.",
"Catalogue - List different fields within civil engineering.",
"Catalogue - List different types of computer hardware.",
"Catalogue - List different types of manufacturing processes.",
"Catalogue - List different types of environmental engineering solutions.",
"Catalogue - List different types of communication tools used by engineers.",
"Catalogue - List different types of technical documents.",
"Catalogue - List different engineering careers and the skills they require."

];


let prompts = [
  "You are an assistant construction manager preparing for your first project meeting. Your supervisor wants to use [the name of one real project scheduling method], but you believe [the name of a different real project scheduling method] would work better. Write about 350 words persuading your supervisor to change plans. Include specific advantages and disadvantages of each method.",
  "You work for a company that manufactures cleaning products. Your manager is considering replacing [the name of one real chemical ingredient] with [the name of another real chemical ingredient]. Write about 350 words explaining whether this change is a good idea. Include information about safety, cost, effectiveness, and environmental impact.",
  "You are the newest electrical engineer on your team. The team currently uses [the name of one real electrical testing instrument], but you recommend [the name of a different real electrical testing instrument]. Write about 350 words persuading the team to make the switch. Explain how each instrument works and why your recommendation is better.",
  "Your company needs to build a new customer website. Your manager has suggested [the name of one real programming language or framework], but you recommend [the name of another real programming language or framework]. Write about 350 words explaining your recommendation. Include examples of companies or projects that use the technology.",
  "You have been asked to recommend [the name of one real bearing, gear, or motor] for a manufacturing machine. Write about 350 words explaining why your choice is better than [the name of another real bearing, gear, or motor]. Discuss performance, maintenance, cost, and expected lifespan.",
  "A homeowner wants to build a new house. They are deciding between [the name of one real building material] and [the name of another real building material] for the exterior. Write about 350 words educating the homeowner about the strengths and weaknesses of each material and recommending one.",
  "A local farm wants to purchase a new irrigation system. Write about 350 words comparing [the name of one real irrigation system or technology] and [the name of another real irrigation system or technology] and recommending the better choice. Include information about installation, maintenance, water use, and long-term costs.",
  "A building project is falling behind schedule. Write about 350 words convincing the project manager to adopt [the name of one real construction management technique or software tool] to improve productivity. Explain how it works and why it would help.",
  "Your factory must choose between [the name of one real water treatment method] and [the name of another real water treatment method]. Write about 350 words recommending one approach to the plant manager. Include technical facts, operating costs, and environmental considerations.",
  "A homeowner wants to install backup power for their house. Write about 350 words explaining whether they should choose [the name of one real standby generator] or [the name of one real battery backup system]. Include product examples and explain the advantages and drawbacks of each.",
  "Your school is deciding which [the name of one real database system] to use for student records. Write about 350 words recommending this option to the technology director. Explain how it compares with [the name of another real database system] and why it best fits the school's needs.",
  "A company is replacing its air compressors. Write about 350 words recommending [the name of one real compressor type or model] over [the name of another real compressor type or model]. Include efficiency, maintenance, noise, and operating costs.",
  "Your architecture firm is choosing [the name of one real green building certification program] for a new office building. Write about 350 words persuading the client to pursue that certification. Explain the requirements, benefits, and potential drawbacks.",
  "A greenhouse owner wants to automate climate control. Write about 350 words recommending [the name of one real environmental control system or technology]. Include specific products or manufacturers and explain how the system improves plant growth.",
  "Your company is considering purchasing [the name of one real construction management software package] instead of [the name of another real construction management software package]. Write about 350 words recommending the better option to company leadership. Discuss scheduling, communication, budgeting, and ease of use.",
  "A plastics manufacturer wants to change to [the name of one real biodegradable material]. Write about 350 words explaining whether the switch is practical. Include manufacturing challenges, costs, and environmental benefits.",
  "A factory is replacing its lighting. Write about 350 words recommending [the name of one real commercial lighting technology or product line]. Explain energy savings, installation costs, maintenance, and expected return on investment.",
  "Your employer needs a new cybersecurity solution. Write about 350 words recommending [the name of one real cybersecurity platform or service] instead of [the name of another real cybersecurity platform or service]. Include features, costs, and situations where each product performs well.",
  "A city is purchasing new buses. Write about 350 words recommending [the name of one real bus technology or fuel type], using [the name of one real bus manufacturer or model] as an example. Explain the benefits and trade-offs compared with other transportation options.",
  "A family farm wants to purchase its first drone. Write about 350 words recommending [the name of one real agricultural drone model] and explaining how it can improve crop management. Include specific features and limitations.",
  "Your company is choosing between [the name of one real concrete mix] and [the name of another real concrete mix] for a bridge project. Write about 350 words recommending one option to the project engineer. Explain the strengths, weaknesses, costs, and expected durability of each mix.",
  "A homeowner wants to install solar panels. Write about 350 words explaining whether [the name of one real solar panel brand or model] is a better choice than [the name of another real solar panel brand or model]. Include efficiency, warranty, cost, and expected lifespan.",
  "Your manufacturing company needs a new CAD software package. Write about 350 words recommending [the name of one real CAD program] over [the name of another real CAD program]. Explain how each program supports engineering design and collaboration.",
  "A local government is replacing an aging water pipeline. Write about 350 words recommending [the name of one real pipe material] over [the name of another real pipe material]. Include installation, maintenance, lifespan, and environmental considerations.",
  "You have been asked to recommend [the name of one real welding process] for a manufacturing project. Write about 350 words explaining why it is the best choice compared to [the name of another real welding process].",
  "Your architecture firm is selecting [the name of one real roofing material] for a public library. Write about 350 words recommending your choice to the client. Include appearance, durability, maintenance, and cost.",
  "A farm wants to reduce fertilizer use. Write about 350 words recommending [the name of one real precision agriculture technology] that could help. Explain how it works and the benefits it provides.",
  "Your employer is choosing between [the name of one real cloud computing provider] and [the name of another real cloud computing provider]. Write about 350 words recommending one provider for the company's new engineering applications.",
  "A warehouse is replacing its forklifts. Write about 350 words recommending [the name of one real forklift model or manufacturer] over [the name of another real forklift model or manufacturer]. Explain the advantages and disadvantages of each option.",
  "Your city wants to install electric vehicle charging stations. Write about 350 words recommending [the name of one real charging station manufacturer or product line]. Include installation requirements, reliability, and maintenance.",
  "A construction company is deciding whether to purchase [the name of one real drone surveying system]. Write about 350 words explaining whether the investment is worthwhile. Include specific products and examples of how they improve surveying.",
  "Your laboratory is replacing its 3D printer. Write about 350 words recommending [the name of one real 3D printer model] over [the name of another real 3D printer model] for producing engineering prototypes.",
  "Your employer wants to standardize on [the name of one real project communication platform]. Write about 350 words recommending your preferred software. Include features that improve teamwork and project organization.",
  "A homeowner wants to install a new heating and cooling system. Write about 350 words comparing [the name of one real HVAC system or brand] and [the name of another real HVAC system or brand] and recommending one.",
  "A factory is considering replacing its conveyor system. Write about 350 words recommending [the name of one real conveyor technology or manufacturer]. Include productivity, maintenance, and safety considerations.",
  "Your architecture firm is choosing [the name of one real insulation material] for a new office building. Write about 350 words recommending your preferred material. Include energy efficiency, installation, cost, and environmental impact.",
  "A local farm wants to improve soil health. Write about 350 words recommending [the name of one real soil testing service or technology]. Explain how it works and how it benefits the farm.",
  "Your company needs to improve cybersecurity training. Write about 350 words recommending [the name of one real cybersecurity awareness platform] instead of [the name of another real cybersecurity awareness platform]. Include specific features and expected outcomes.",
  "A machine shop wants to purchase a new CNC machine. Write about 350 words recommending [the name of one real CNC machine manufacturer or model]. Explain why it best meets the company's needs.",
  "A school district is building a new STEM laboratory. Write about 350 words recommending [the name of one real laboratory equipment supplier]. Include product quality, customer support, and value.",
  "Your company is choosing between [the name of one real web hosting service] and [the name of another real web hosting service] for a new engineering website. Write about 350 words recommending one option and explaining your reasoning.",
  "A homeowner wants to install smart home technology. Write about 350 words recommending [the name of one real smart home ecosystem] over [the name of another real smart home ecosystem]. Include compatibility, ease of use, security, and cost.",
  "A manufacturing plant wants to reduce workplace injuries. Write about 350 words recommending [the name of one real safety management program, certification, or technology]. Explain how it improves safety.",
  "Your construction company is selecting [the name of one real laser measuring or layout tool]. Write about 350 words recommending your preferred instrument and explaining why it is worth the investment.",
  "A food processing plant needs to replace its refrigeration equipment. Write about 350 words recommending [the name of one real refrigeration technology or manufacturer]. Include efficiency, maintenance, and operating costs.",
  "Your engineering team is deciding between [the name of one real version control platform] and [the name of another real version control platform]. Write about 350 words recommending one platform for software development and explaining why it better supports collaboration.",
  "A community is planning a new playground. Write about 350 words recommending [the name of one real playground surface material] over [the name of another real playground surface material]. Include safety, maintenance, accessibility, and long-term costs.",
  "A farm cooperative wants to purchase a new grain dryer. Write about 350 words recommending [the name of one real grain dryer manufacturer or model]. Explain its advantages compared to [the name of another real grain dryer manufacturer or model].",
  "Your employer is replacing office computers used for engineering design. Write about 350 words recommending [the name of one real workstation manufacturer or product line] over [the name of another real workstation manufacturer or product line]. Include processing power, reliability, and value.",
  "A city is planning to improve pedestrian safety at busy intersections. Write about 350 words recommending [the name of one real traffic signal technology, crossing system, or traffic management solution]. Explain how it works, discuss its costs, and persuade city officials that it is the best investment."
];

let last_prompt = -1
function pick_prompt() {
    let random_index;
    do {
        random_index = Math.floor(Math.random() * prompt_array.length);
    } while (random_index === last_prompt);
    last_prompt = random_index;
    document.getElementById("prompt").innerHTML = prompt_array[random_index];
}